export { ReactComponent as FlatIcon } from "./FlatIcon.svg"
export { ReactComponent as HouseIcon } from "./HouseIcon.svg"
export { ReactComponent as EmailIcon } from "./EmailIcon.svg"
export { ReactComponent as FacebookIcon } from "./FacebookIcon.svg"
export { ReactComponent as PhoneIcon } from "./PhoneIcon.svg"
export { ReactComponent as InstagramIcon } from "./InstagramIcon.svg"