export { ReactComponent as FlatIcon } from "./FlatIcon.svg"
export { ReactComponent as HouseIcon } from "./HouseIcon.svg"
export { ReactComponent as EmailIcon } from "./EmailIcon.svg"
export { ReactComponent as FacebookIcon } from "./FacebookIcon.svg"
export { ReactComponent as PhoneIcon } from "./PhoneIcon.svg"
export { ReactComponent as InstagramIcon } from "./InstagramIcon.svg"
export { ReactComponent as DoubleArrow } from "./DoubleArrow.svg"
export { ReactComponent as DeclineCross} from "./DeclineCross.svg"
export { ReactComponent as DoubleArrowLeft} from "./DoubleArrowLeft.svg"
export { ReactComponent as DoubleArrowRight} from "./DoubleArrowRight.svg"
export { ReactComponent as ArrowLeft} from "./ArrowLeft.svg"
export { ReactComponent as ArrowRight} from "./ArrowRight.svg"