export { Header } from "./header/Header"
export { Navbar } from "./navbar/Navbar"
export { Main } from "./main/Main"
export { Footer } from "./footer/Footer"
export { Services } from "./services/Services"
export { AboutUs } from "./aboutUs/AboutUs"
export { Prefooter } from "./prefooter/Prefooter"
export { References } from "./references/References"